CREATE DATABASE `db3`;

-- db3.tb3 definition

CREATE TABLE `tb3` (
  `id` int NOT NULL AUTO_INCREMENT,
  `txt` varchar(300) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;